/*******************************************************
* Creator: Martin Johansson
* Portability: Native
*-------------------------------------------------------
*
*******************************************************/

#ifndef __EM_WIN_SMPTE_VIDEO_TRANSITION_NAMES
#define __EM_WIN_SMPTE_VIDEO_TRANSITION_NAMES

typedef struct _SMPTEPost
{
	int m_vNumber;
	char *m_vName;
} SMPTEPost;

static SMPTEPost g_SMPTEName[] = 
{{1, "Slide horizontal"},
{2, "Slide vertical"},
{3, "Top left"},
{4, "Top right"},
{5, "Bottom right"},
{6, "Bottom left"},
{7, "Four corner"},
{8, "Four box"},
{21, "Barn vertical"},
{22, "Barn horizontal"},
{23, "Top center"},
{24, "Right center"},
{25, "Bottom center"},
{26, "Left center"},
{41, "Diagonal left down"},
{42, "Diagonal right down"},
{43, "Vertical bow tie"},
{44, "Horizontal bow tie"},
{45, "Diagonal left out"},
{46, "Diagonal right out"},
{47, "Diagonal cross"},
{48, "Diagonal box"},
{61, "Filled V"},
{62, "Filled V right"},
{63, "Filled V bottom"},
{64, "Filled V left"},
{65, "Hollow V"},
{66, "Hollow V right"},
{67, "Hollow V bottom"},
{68, "Hollow V left"},
{71, "Vertical zig zag"},
{72, "Horizontal zig zag"},
{73, "Vertical barn zig zag"},
{74, "Horizontal barn zig zag"},
{101, "Rectangle"},
{102, "Diamond"},
{103, "Triangle"},
{104, "Triangle right"},
{105, "Triangle upside down"},
{106, "Triangle left"},
{107, "Arrowhead"},
{108, "Arrowhead right"},
{109, "Arrowhead upside down"},
{110, "Arrowhead left"},
{111, "Pentagon"},
{112, "Pentagon upside down"},
{113, "Hexagon"},
{114, "Hexagon side"},
{119, "Circle"},
{120, "Oval"},
{121, "Oval side"},
{122, "Cat eye"},
{123, "Cat eye side"},
{124, "Round rect"},
{125, "Round rect side"},
{127, "4 point star"},
{128, "5 point star"},
{129, "6 point star"},
{130, "Heart"},
{131, "Keyhole"},
{201, "Rotating top"},
{202, "Rotating right"},
{203, "Rotating bottom"},
{204, "Rotating left"},
{205, "Rotating top bottom"},
{206, "Rotating left right"},
{207, "Rotating quadrant"},
{211, "Top to bottom 180°"},
{212, "Right to left 180°"},
{213, "Top to bottom 90°"},
{214, "Right to left 90°"},
{221, "Top 180°"},
{222, "Right 180°"},
{223, "Bottom 180°"},
{224, "Left 180°"},
{225, "Counter rotating top bottom"},
{226, "Counter rotating left right"},
{227, "Double rotating top bottom"},
{228, "Double rotating left right"},
{231, "V Open top"},
{232, "V Open right"},
{233, "V Open bottom"},
{234, "V Open left"},
{235, "V Open top bottom"},
{236, "V Open left right"},
{241, "Rotating top left"},
{242, "Rotating bottom left"},
{243, "Rotating bottom right"},
{244, "Rotating top right"},
{245, "Rotating top left bottom right"},
{246, "Rotating bottom left top right"},
{251, "Rotating top left right"},
{252, "Rotating left top bottom"},
{253, "Rotating bottom left right"},
{254, "Rotating right top bottom"},
{261, "Rotating double center right"},
{262, "Rotating double center top"},
{263, "Rotating double center top bottom"},
{264, "Rotating double center left right"},
{301, "Horizontal matrix"},
{302, "Vertical matrix"},
{303, "Top left diagonal matrix"},
{304, "Top right diagonal matrix"},
{305, "Bottom right diagonal matrix"},
{306, "Bottom left diagonal matrix"},
{310, "Clockwise top left matrix"},
{311, "Clockwise top right matrix"},
{312, "Clockwise bottom right matrix"},
{313, "Clockwise bottom left matrix"},
{314, "Counter clockwise top left matrix"},
{315, "Counter clockwise top right matrix"},
{316, "Counter clockwise bottom right matrix"},
{317, "Counter clockwise bottom left matrix"},
{320, "Vertical start top matrix"},
{321, "Vertical start bottom matrix"},
{322, "Vertical start top opposite matrix"},
{323, "Vertical start bottom opposite matrix"},
{324, "Horizontal start left matrix"},
{325, "Horizontal start right matrix"},
{326, "Horizontal start left opposite matrix"},
{327, "Horizontal start right opposite matrix"},
{328, "Double diagonal top right matrix"},
{329, "Double diagonal bottom right matrix"},
{340, "Double spiral Top matrix"},
{341, "Double spiral bottom matrix"},
{342, "Double spiral left matrix"},
{343, "Double spiral right matrix"},
{344, "Quad spiral vertical matrix"},
{345, "Quad spiral horizontal matrix"},
{350, "Vertical waterfall left matrix"},
{351, "Vertical waterfall right matrix"},
{352, "Horizontal waterfall left matrix"},
{353, "Horizontal waterfall right matrix"},
{-1,  "Dummy"}};

#endif